# Generated by Django 5.0 on 2024-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='slideshow')),
            ],
            options={
                'verbose_name': 'slider',
                'verbose_name_plural': 'slide',
                'db_table': 'slideshow_image',
                'ordering': ['-id'],
            },
        ),
    ]
